SELECT 
GENRE,
ROUND(SUM(NA_SALES)*100/SUM(GLOBAL_SALES),1) as pct_NA,
ROUND(SUM(EU_SALES)*100/SUM(GLOBAL_SALES),1) as pct_EU,
ROUND(SUM(JP_SALES)*100/SUM(GLOBAL_SALES),1) as pct_JP,
ROUND(SUM(OTHER_SALES)*100/SUM(GLOBAL_SALES),1) as pct_OTHER
FROM [analysis-games].dbo.VideoGameSales
WHERE Global_Sales > 0
Group By Genre
Having Genre IS NOT NULL
Order BY pct_NA DESC